spring:
  application:
    name: "account-statistic"

  r2dbc:
    url: "${GD2SPRING_POSTGRES_URL:r2dbc:postgresql://localhost:5432/dev}"
    username: "${GD2SPRING_POSTGRES_USERNAME:dev}"
    password: "${GD2SPRING_POSTGRES_PASSWORD:dev}"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8081/eureka"

